### ISSUE TITLE
Is there a diff generator?

### ISSUE THREAD

**Issue by hoijui** [CriticMarkup/CriticMarkup-toolkit#40]
.. as in: two files go in, one CriticMarkup "annotated" file comes out.

This would be very useful for an alternative diff view on GitHub, GitLab and the like.

**Comment by sorenoneill** [comment]
+1

This would be a GREAT addition!

Going from git diff chunks
```
@@ -1 +1 @@
-First version
+Second version
```

...to Critic Markup...
`{~~First->Second~~} version`

...and then to 'cleaned up' regular markdown
`Second version`

That would be an absolute killer feature for those of us, who use markdown to prepare scientific manuscripts in collaboration with colleagues -- including those who do not use markdown. 

I would allow us to 
a) use git for versioning
b) prepare a CriticMarkup version where changes are highlighted and
c) prepare a final version with changes 'implemented'.

**Comment by a-vrma** [comment]
Maybe https://github.com/davidar/pandiff?

**Comment by hoijui** [comment]
That looks like it, thank you! :-)

I made a pull request to add it to the README:
https://github.com/CriticMarkup/CriticMarkup-toolkit/issues/40

**Comment by reagle** [comment]
Was the pull request accepted? Can this be closed?

**Comment by cknoll** [comment]
Currently the PR is still open: #42 

(in their last post @hoijui linked this current issue, where probably the PR-link was intended)
