### ISSUE TITLE
installing and adding a comment causes an error

### ISSUE THREAD

**Issue by kevboh** [CriticMarkup/CriticMarkup-toolkit#52]
I installed via BRAT and added a comment (`{>>test<<}`) to an existing note. When nothing seemed to change I opened dev tools and saw this error:

<img width="470" alt="image" src="https://github.com/CriticMarkup/CriticMarkup-toolkit/assets/436032/612a8406-9a0e-4568-967e-324a2f3f1378">

Any other config or incantations I need to do to get it working?

**Comment by Fevol** [comment]
Hi @kevboh, I happened to stumble on this issue - I think you meant to open it on the [Commentator plugin](https://github.com/Fevol/obsidian-criticmarkup) page? This repository is for the CriticMarkup syntax itself (and unrelated to the plugin)

**Comment by kevboh** [comment]
Oooohhhh whoops, I did! I'll move there, my bad.
